apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-openwebui-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-kb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.openwebui.storage.size }}
