apiVersion: v2
appVersion: 1.2.0
dependencies:
- alias: postgresql
  condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.6.6
description: AI Analytics Agent — Ask questions about your website traffic in natural
  language via WhatsApp, Telegram, or Slack
name: ai-analytics-agent
type: application
version: 1.2.0
