apiVersion: v2
appVersion: 26.1.4
dependencies:
- name: keycloak
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 25.2.0
description: 'Keycloak Identity and Access Management — single-click deploy on E2E
  Marketplace. '
name: keycloak
type: application
version: 1.0.2
