apiVersion: v2
appVersion: 3.13.7
dependencies:
- name: rabbitmq
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.0.14
description: RabbitMQ message broker with management UI and exposed credentials
name: rabbitmq-e2e
type: application
version: 1.0.0
