apiVersion: v2
appVersion: 9.11.2
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.38
description: Mattermost team messaging platform with PostgreSQL
name: mattermost
type: application
version: 1.0.0
