image:
  repository: quay.io/prometheus/prometheus
  tag: v2.53.4
  pullPolicy: IfNotPresent

storage:
  size: "10Gi"
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

nodeSelector: {}
