probe:
  url1: ""
  url2: ""
  url3: ""
  interval: "30s"
  timeout: "10s"

prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.53.4
    pullPolicy: IfNotPresent
  retention: "15d"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

blackbox:
  image:
    repository: quay.io/prometheus/blackbox-exporter
    tag: v0.25.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

grafana:
  image:
    repository: registry.e2enetworks.net/marketplace-blueprint/grafana
    tag: "11.3.3"
    pullPolicy: IfNotPresent
  adminUser: ""
  adminPassword: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

storage:
  prometheus:
    size: "5Gi"
  grafana:
    size: "1Gi"
  accessMode: ReadWriteOnce

nginx:
  image:
    repository: registry.e2enetworks.net/marketplace-blueprint/nginx
    tag: "1.27-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "200m"
      memory: "64Mi"

nodeSelector: {}
