apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pb.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.probe.interval }}
      evaluation_interval: {{ .Values.probe.interval }}

    scrape_configs:
      - job_name: 'website-probe'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
{{- if .Values.probe.url1 }}
            - {{ .Values.probe.url1 | quote }}
{{- end }}
{{- if .Values.probe.url2 }}
            - {{ .Values.probe.url2 | quote }}
{{- end }}
{{- if .Values.probe.url3 }}
            - {{ .Values.probe.url3 | quote }}
{{- end }}
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: {{ .Release.Name }}:80


  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: {{ .Values.probe.timeout }}
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: []
          method: GET
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: false
