apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-prometheus-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.prometheus.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.grafana.size }}
