apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cufolio.fullname" . }}-data
  labels:
    {{- include "cufolio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cufolio.fullname" . }}-cache
  labels:
    {{- include "cufolio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.cacheSize }}
