apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ollama-models
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ollama.storage.size }}
  {{- if .Values.ollama.storage.storageClass }}
  storageClassName: {{ .Values.ollama.storage.storageClass }}
  {{- end }}
