apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
data:
  webui-secret-key: {{ include "open-webui.secretKey" . }}
  webui-admin-email: {{ .Values.webui.adminEmail | b64enc }}
  webui-admin-password: {{ .Values.webui.adminPassword | b64enc }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.anthropicApiKey | b64enc }}
  GROQ_API_KEY: {{ .Values.groqApiKey | b64enc }}
  GOOGLE_API_KEY: {{ .Values.googleApiKey | b64enc }}
  FIREWORKS_API_KEY: {{ .Values.fireworksApiKey | b64enc }}
  MISTRAL_API_KEY: {{ .Values.mistralApiKey | b64enc }}
  PERPLEXITY_API_KEY: {{ .Values.perplexityApiKey | b64enc }}
