apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.webuiHost" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "open-webui.webuiSelectorLabels" . | nindent 4 }}
