apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.ollamaHost" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: ollama
  selector:
    {{- include "open-webui.ollamaSelectorLabels" . | nindent 4 }}
