apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-openclaw-home
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.openclaw.storage.size }}
