apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-elasticsearch
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
