{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-kafka
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
{{- end }}
