apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vss.fullname" . }}-nim-cosmos-cache
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: nim-cosmos
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.nim.cosmos.cacheSize }}
