apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-redis
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
