apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-vss-agent
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vss-agent
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    app.kubernetes.io/name: vss-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.vssAgent.port }}
      targetPort: {{ .Values.vssAgent.port }}
      {{- if not .Values.ingress.enabled }}
      nodePort: {{ .Values.vssAgent.nodePort }}
      {{- end }}
