{{- if .Values.vst.sdr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-vst-sdr
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-sdr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vst-sdr
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: {{ .Values.vst.sdr.port }}
      targetPort: {{ .Values.vst.sdr.port }}
{{- end }}
