apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-vst-ingress
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-ingress
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    app.kubernetes.io/name: vst-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.vst.ingress.port }}
      targetPort: {{ .Values.vst.ingress.port }}
      {{- if not .Values.ingress.enabled }}
      nodePort: {{ .Values.vst.ingress.nodePort }}
      {{- end }}
