apiVersion: v1
kind: Service
metadata:
  name: {{ include "vss.fullname" . }}-vst-postgres
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vst-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.vst.postgres.port }}
      targetPort: {{ .Values.vst.postgres.port }}
