{{- if .Values.vst.envoy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vss.fullname" . }}-vst-envoy
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vst-envoy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vst-envoy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: vst-envoy
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
        - name: {{ include "vss.fullname" . }}-nvcr-pull
      containers:
        - name: vst-envoy
          image: {{ .Values.vst.envoy.image }}
          command:
            - /usr/local/bin/envoy
            - -c
            - /etc/envoy/envoy.yaml
            - --concurrency
            - "16"
            - --base-id
            - "1"
          env:
            - name: WDM_WL_REDIS_SERVER
              value: {{ include "vss.redisHost" . | quote }}
            - name: CONTAINER_NAME
              value: envoy-streamprocessing
            - name: WDM_WL_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: WDM_KFK_BOOTSTRAP_URL
              value: {{ include "vss.kafkaBootstrap" . | quote }}
            - name: WDM_WL_OBJECT_NAME
              value: streamprocessing-ms
            - name: ENVOYROUTEHEADER
              value: streamid
            - name: NOHEADERTARGETCONTAINER
              value: streamprocessing-ms-1
          ports:
            - containerPort: {{ .Values.vst.envoy.port }}
              name: http
            - containerPort: 9901
              name: admin
          resources:
            {{- toYaml .Values.vst.envoy.resources | nindent 12 }}
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "vss.fullname" . }}-vst-envoy-config
{{- end }}
