apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vss.fullname" . }}-vst-postgres-db
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vst.postgres.dbSize }}
