apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vss.fullname" . }}-vst-sensor-data
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-sensor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.vst.sensor.dataSize }}
