apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vss.fullname" . }}-vst-sp-data
  labels:
    {{- include "vss.labels" . | nindent 4 }}
    app.kubernetes.io/component: vst-streamprocessing
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.vst.streamprocessing.dataSize }}
