replicaCount: 1

image:
  repository: redis
  tag: "7.4.1-alpine"
  pullPolicy: IfNotPresent

auth:
  password: ""

service:
  type: NodePort
  port: 6379
  nodePort: ""

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
