apiVersion: v2
appVersion: 2.516.2
dependencies:
- name: jenkins
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.6.17
description: Jenkins CI/CD with Apache Maven pre-installed. One-click deploy on E2E
  Marketplace.
name: jenkins-maven
type: application
version: 1.0.7
