global:
  imagePullSecrets:
    - registry-pull-secret
  security:
    allowInsecureImages: true

clickhouse:
  image:
    registry: registry.e2enetworks.net
    repository: marketplace-blueprint/clickhouse
    tag: 25.7.5-debian-12-r0
    pullPolicy: IfNotPresent
  keeper:
    image:
      registry: registry.e2enetworks.net
      repository: marketplace-blueprint/clickhouse-keeper
      tag: 25.7.5-debian-12-r0
      pullPolicy: IfNotPresent
  defaultInitContainers:
    volumePermissions:
      image:
        registry: registry.e2enetworks.net
        repository: marketplace-blueprint/os-shell
        tag: 12-debian-12-r65
        pullPolicy: IfNotPresent
  auth:
    username: "default"
    password: ""
  shards: 1
  replicaCount: 1
  persistence:
    size: "20Gi"
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "100m"
      memory: "1Gi"
