# NATS — example values
# helm install nats blueprints/nats -f my-values.yaml

service:
  type: NodePort

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 64Mi

# auth:
#   enabled: true
#   token: "YOUR-AUTH-TOKEN"
