# relok8s image hints file
# This file makes this Helm Chart relocatable by relok8s
# More info here https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes
#
# tomcat chart

# tomcat image
- "{{.image.registry}}/{{.image.repository}}:{{.image.tag}}"
# jmx-exporter image
- "{{.metrics.jmx.image.registry}}/{{.metrics.jmx.image.repository}}:{{.metrics.jmx.image.tag}}"
# os-shell image
- "{{.volumePermissions.image.registry}}/{{.volumePermissions.image.repository}}:{{.volumePermissions.image.tag}}"

