annotations:
  fips: "true"
  images: |
    - name: jmx-exporter
      version: 1.5.0
      image: registry-1.docker.io/bitnami/jmx-exporter:latest
    - name: os-shell
      version: "5"
      image: registry-1.docker.io/bitnami/os-shell:latest
    - name: tomcat
      version: 11.0.20
      image: registry-1.docker.io/bitnami/tomcat:latest
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 11.0.20
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.37.0
description: Apache Tomcat is an open-source web server designed to host and run Java-based
  web applications. It is a lightweight server with a good performance for applications
  running in production environments.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/tomcat/img/tomcat-stack-220x234.png
keywords:
- tomcat
- java
- http
- web
- application server
- jsp
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: tomcat
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/tomcat
version: 13.4.8
