apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-plane-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aipm.labels" . | nindent 4 }}
data:
  DEBUG: "0"
  DJANGO_SETTINGS_MODULE: "plane.settings.production"
  GUNICORN_WORKERS: "2"
  ENABLE_SIGNUP: "1"
  USE_MINIO: "0"
  FILE_SIZE_LIMIT: "5242880"
  WEB_URL: "http://{{ .Release.Name }}-api:8000"
  CORS_ALLOWED_ORIGINS: ""
  CORS_ALLOW_ALL_ORIGINS: "True"
  POSTGRES_HOST: "{{ .Release.Name }}-postgres"
  POSTGRES_PORT: "5432"
  PGHOST: "{{ .Release.Name }}-postgres"
  PGPORT: "5432"
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "6379"
