{{- if .Values.kafkaUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka-ui-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kafka-ui-{{ .Release.Name }}
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Release.Name }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ .Release.Name }}-controller-0.{{ .Release.Name }}-controller-headless.{{ .Release.Namespace }}.svc.cluster.local:9094
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
{{- end }}
