{{- if and .Values.kafkaUi.enabled .Values.kafkaUi.lbIpDashes }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  ingressClassName: haproxy
  rules:
    - host: kafka-ui-{{ .Release.Name }}.{{ .Values.kafkaUi.lbIpDashes }}.{{ .Values.kafkaUi.domainSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui-{{ .Release.Name }}
                port:
                  number: 80
{{- end }}
